# ===================================
#  Relation Behavior Config
# ===================================

bouts:
    label: Bouts
    deferredBinding: true
    view:
        list: $/ajslim/fencingactions/models/bout/columns.yaml
        form: $/ajslim/fencingactions/models/bout/fields.yaml
        recordUrl: ajslim/fencingactions/bouts/update/:id
        toolbarButtons: create|delete
    manage:
        form: $/ajslim/fencingactions/models/bout/fields.yaml
        list: $/ajslim/fencingactions/models/bout/columns.yaml
        recordsPerPage: 10

actions:
    label: Actions
    deferredBinding: true
    view:
        list: $/ajslim/fencingactions/models/action/columns.yaml
        form: $/ajslim/fencingactions/models/action/fields.yaml
        recordUrl: ajslim/fencingactions/actions/update/:id
        toolbarButtons: create|delete
    manage:
        form: $/ajslim/fencingactions/models/action/fields.yaml
        list: $/ajslim/fencingactions/models/action/columns.yaml
        recordsPerPage: 10